/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hex_IA */

#ifndef _Included_hex_IA
#define _Included_hex_IA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hex_IA
 * Method:    jouerCoupFacile
 * Signature: (Ljava/lang/String;C)[I
 */
JNIEXPORT jintArray JNICALL Java_hex_IA_jouerCoupFacile
  (JNIEnv *, jclass, jstring, jchar);

/*
 * Class:     hex_IA
 * Method:    jouerCoupMoyen
 * Signature: (Ljava/lang/String;C)[I
 */
JNIEXPORT jintArray JNICALL Java_hex_IA_jouerCoupMoyen
  (JNIEnv *, jclass, jstring, jchar);

/*
 * Class:     hex_IA
 * Method:    jouerCoupDifficile
 * Signature: (Ljava/lang/String;C)[I
 */
JNIEXPORT jintArray JNICALL Java_hex_IA_jouerCoupDifficile
  (JNIEnv *, jclass, jstring, jchar);

/*
 * Class:     hex_IA
 * Method:    jouerCoupImpossible
 * Signature: (Ljava/lang/String;C)[I
 */
JNIEXPORT jintArray JNICALL Java_hex_IA_jouerCoupImpossible
  (JNIEnv *, jclass, jstring, jchar);

#ifdef __cplusplus
}
#endif
#endif
