/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Plateau */

#ifndef _Included_Plateau
#define _Included_Plateau
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Plateau
 * Method:    creerGraphe
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Plateau_creerGraphe
  (JNIEnv *, jclass, jint);

/*
 * Class:     Plateau
 * Method:    rentrerCoup
 * Signature: (Ljava/lang/String;CII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Plateau_rentrerCoup
  (JNIEnv *, jclass, jstring, jchar, jint, jint);

/*
 * Class:     Plateau
 * Method:    verifierGagnant
 * Signature: (Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_Plateau_verifierGagnant
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Plateau
 * Method:    annulerDernierCoup
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Plateau_annulerDernierCoup
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     Plateau
 * Method:    verifierCaseVide
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jchar JNICALL Java_Plateau_verifierCase
  (JNIEnv *, jclass, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
