/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InterfaceAvecC */

#ifndef _Included_InterfaceAvecC
#define _Included_InterfaceAvecC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InterfaceAvecC
 * Method:    creerGraphe
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InterfaceAvecC_creerGraphe
  (JNIEnv *, jclass, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    rentrerCoup
 * Signature: (Ljava/lang/String;CII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InterfaceAvecC_rentrerCoup
  (JNIEnv *, jclass, jstring, jchar, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    verifierGagnant
 * Signature: (Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_InterfaceAvecC_verifierGagnant
  (JNIEnv *, jclass, jstring);

/*
 * Class:     InterfaceAvecC
 * Method:    annulerDernierCoup
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InterfaceAvecC_annulerDernierCoup
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    verifierCaseVide
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jchar JNICALL Java_InterfaceAvecC_verifierCase
  (JNIEnv *, jclass, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
